
/**
 *
 * @author Soravath Mengseng
 */
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
 
package ElevatorMovementSimulator;

import javax.swing.JTextArea;

/**
 *
 * @author Sarawat
 */
public class SubFrame extends javax.swing.JFrame {

    private ControllerDemo controller;
    
    
    
    public SubFrame( ControllerDemo controller) {
       this.controller = controller;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jTfFloor = new javax.swing.JTextField();
        jTfElevator = new javax.swing.JTextField();
        jLFloor = new javax.swing.JLabel();
        jLElevator = new javax.swing.JLabel();
        jTfMaxVisitor = new javax.swing.JTextField();
        jLMaxVisitor = new javax.swing.JLabel();
        jLInitialVisitor = new javax.swing.JLabel();
        jTfInitialVisitor = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTAreaStatus = new javax.swing.JTextArea();
        jLshowStatus = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTfElevator.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTfElevatorActionPerformed(evt);
            }
        });

        jLFloor.setText("Floors");

        jLElevator.setText("Elevators");

        jTfMaxVisitor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTfMaxVisitorActionPerformed(evt);
            }
        });

        jLMaxVisitor.setText("Max Visitor");

        jLInitialVisitor.setText("Initial Visitor");

        jTfInitialVisitor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTfInitialVisitorActionPerformed(evt);
            }
        });

        jTAreaStatus.setEditable(false);
        jTAreaStatus.setColumns(20);
        jTAreaStatus.setRows(5);
        jScrollPane1.setViewportView(jTAreaStatus);

        jLshowStatus.setText("Visitor's Status");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLElevator)
                            .addComponent(jTfFloor, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTfElevator, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLMaxVisitor)
                            .addComponent(jLFloor))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLshowStatus))
                        .addGap(31, 31, 31))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTfMaxVisitor, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTfInitialVisitor, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLInitialVisitor))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jLshowStatus))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLFloor)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jTfFloor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLElevator)
                        .addGap(4, 4, 4)
                        .addComponent(jTfElevator, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLMaxVisitor)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTfMaxVisitor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLInitialVisitor)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTfInitialVisitor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(19, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTfElevatorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTfElevatorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTfElevatorActionPerformed

    private void jTfMaxVisitorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTfMaxVisitorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTfMaxVisitorActionPerformed

    private void jTfInitialVisitorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTfInitialVisitorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTfInitialVisitorActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SubFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SubFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SubFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SubFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
       // java.awt.EventQueue.invokeLater(new Runnable() {
           // public void run() {
              //  new SubFrame().setVisible(true);
            //}
        //});
    }
    public void setFloors( String floor){
    jTfFloor.setText(floor);
    
    }
      
    public void setElevator(String elevator){
        jTfElevator.setText(elevator);
    }
    
    public void setMaxVisitor(String maxVisitor){
        jTfMaxVisitor.setText(maxVisitor);
        
    }
    
    public void setInitialVisitor(String initialVisitor){
        jTfInitialVisitor.setText(initialVisitor);
    }
    
    public int getFloors(){
        
        int floor = Integer.parseInt(jTfFloor.getText());
        return floor;    
    }
    
    public int getElevator(){
        int elevator = Integer.parseInt(jTfElevator.getText());
        return elevator;    
    }
    
    public int getMaxVisitor(){
      int maxVisitor = Integer.parseInt(jTfMaxVisitor.getText());
        return maxVisitor;    
    }
    
     public int getInitialVisitor(){
        int initialVisitor = Integer.parseInt(jTfInitialVisitor.getText());
        return initialVisitor;    
    }
    
    public void showStatus( String status){
      jTAreaStatus.setText(status);
        
    }
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLElevator;
    private javax.swing.JLabel jLFloor;
    private javax.swing.JLabel jLInitialVisitor;
    private javax.swing.JLabel jLMaxVisitor;
    private javax.swing.JLabel jLshowStatus;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTAreaStatus;
    private javax.swing.JTextField jTfElevator;
    private javax.swing.JTextField jTfFloor;
    private javax.swing.JTextField jTfInitialVisitor;
    private javax.swing.JTextField jTfMaxVisitor;
    // End of variables declaration//GEN-END:variables
}
